# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            RealTimeThing
tagline:           The Moment
url:              http://facebook/youchange
paginate:         1
baseurl:          /
author:
  name:           Yuchuan Weng
  url:
  email:          cts734@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


